spring:
  datasource:
    url: jdbc:mysql://192.168.25.131:3306/jpa?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


